### ISSUE TITLE
Issue Number Thirteen

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#13]
Auto-rejected, of course, for being #13.

**Comment by rlaemmel** [comment]
Ok, I saw that Vadim was unarchiving the zip file so that now all files are now "native" files in this repo. 

This triggers the question, which perhaps the reviewer could kindly try to answer, as to whether it may be better to bind all the paper URLs to this repo rather than to the primary YAS repo. 

Pros:
- No changes are applied to the sle16 repo; so things are more reproducible?
Cons:
- If the artefacts get improved then this will be less discoverable.
