### ISSUE TITLE
[benelellam] Efficient Data Partitioning

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#15]
Submitted by @amine-ben to https://github.com/grammarware/sle16/tree/master/benelellam

**Comment by dstrueber** [comment]
The usage instructions for this artifact are generally clear and easy-to-follow, yet I'm stuck while reproducing them, as the step "Checking Hadooop/Hbase Envs" doesn't behave like it should. I'm able to retrieve the master IP using the "docker inspect" comment, but the Hadoop and HBase UIs cannot be loaded in my browser when using the given URLs.

Disclaimer: I use Windows 10 + CygWin + Docker. I also tried using a Linux VM via VirtualBox, but wasn't able to launch the VM as I had to deal with system crashes during VM startup. No Linux machine here, sorry.

**Comment by silvalex** [comment]
I am actually having the exact same experience. I agree that the instructions were clear and I did not have any problem following them, but I also experienced the same issue with the step of "Checking Hadoop/HBase Envs", i.e. despite successfully retrieving the master IP I am unable to load the UIs in my browser. I was also wondering, how much time (roughly) should the start-hadoop.sh script take to run? In my case it took about two hours, which made it a bit more difficult to explore and test some different commands/configurations.

I am using Mac OS X and I tried the instructions with both Docker for Mac and Docker Toolbox to no avail unfortunately.

**Comment by amine-ben** [comment]
Hi all, 

In order to make the UI facility work, you need to set up an ssh channel with dynamic port forwarding  between your machine and the one that hosts docker. Then set up a proxy configuration in your browser according to these parameters (especially port number).
To avoid this unnecessary configuration, I provided a different way to check the Hadoop/HBase environments. Please check the README file. 

@dstrueber : Two hours is a bit too much! The Hadoop/Hbase daemons should run in less than a minute. Could you please tell me which daemon exactly takes time to run ?

**Comment by dstrueber** [comment]
Hi! Thanks for providing the alternative instructions for checking  Hadoop and HBase, they did the trick for me.

Concerning your question: I didn't have problems with start-hadoop.sh before (@silvalex did).

I have now executed the script for performing the experiments (run-all-class.sh). As of now, it seems to work fine: the console output says that several runs of the experiment have been performed already. I wonder, though, if you could give us any reference for  the expected running time, since it's running for two hours now already,  and there's  no direct feedback on the overall progress of the experiment.

**Comment by tdegueul** [comment]
The submitted artefact consists of two docker images and a Shell script to automatically run them.

I encountered no major problem in the use of the artefact. In fact, providing the environment (ATL, ATL-MR, Hadoop, etc.) and the experiment in the form of a docker container makes it easy to reproduce the results given in the paper. I cannot imagine the pain of having to set up all these technologies by myself on my computer and make them cooperate.

The documentation is provided in the form of a README which is easy to read and to follow. The first results I obtained match the results presented in Table 3 of the associated paper (although it is a bit cumbersome to read the produced log files and look for the appropriate counters in the middle of many other things). I was however not able to go through all the experiment (the 7th run never ended after waiting about one hour). This is likely because of my computer which got overwhelmed after a while (memory + swap full, freezes).

My understanding is that it would be hard to easily reuse the provided tool on different transformations/languages/models as all of them are "hidden" in the docker images. It's also hard to read/modify the transformations and models without proper UI support (e.g. an Eclipse workspace). Nonetheless, as said above, I appreciate the effort of putting the artefact in docker images to ease the reproducibility of the experiment.

**Comment by dstrueber** [comment]
Review: 

The instructions for this artifact are detailed and easy to follow. The prerequisites are documented clearly, with a small exception: in addition to the mentioned tools, a bash environment is required.

Using the instructions, I was able to reproduce the experiments mentioned in the paper for a few experimental runs. During the subsequent runs, I received error messages which I believe are related to insufficient memory. I believe it's fair to assume that I could reproduce the remaining results on a more powerful machine.

Using a Docker cluster was generally a good idea to avoid reproducibility pitfalls related to the execution environment. I need to mention that in my first attempts to make the Docker cluster run, I had some issues apparently related to the JVM memory size. These issues  disappeared when I provided Docker a larger share of my main memory.

Generally, it would be very helpful if the hardware set-up and execution times of the past experiments could be listed somewhere, so that researchers interested in reproducing the experiments know what to expect.

Concerning the ease for potential users of the approach, the authors provide detailed instructions for changing the parameters of the transformation to be executed, in particular, the input model and transformation rules. I think it should be easy to transfer the contents from the Docker container to another file system, although then of course, the user needs to set-up the environment again.

Altogether, this is a well-documented, consistent and useful artifact.

**Comment by silvalex** [comment]
Thank you @amine-ben for the response. This time the start-hadoop.sh script ran within a minute, so (un)fortunately I cannot tell what caused the original slowdown. I suspect it was related to my installation of Docker (I uninstalled and then reinstalled Docker for Mac). Thank you also for providing the alternative way of checking Hadoop and HBase; it worked just as expected.

Thank you @dstrueber for pointing out the need to provide a larger share of the memory to Docker. It made me realise why the JVM was unhappy.

The experiments are now running and I should hopefully be getting some results soon.

**Comment by silvalex** [comment]
Review:

This artifact was provided for the paper entitled "Efficient Model Partitioning for Distributed Model Transformations", and it shows an example of transformations performed using the data distribution algorithm proposed in this work. The artifact was packaged in Docker, and it is built on top of HBase. The instructions for setup and execution are easy to follow, and thanks to the packaging in Docker there are no major setup headaches.

Even though I could get the experiment script discussed in Section 5 of the paper to rerun, perhaps my computer is just not powerful enough to handle the computation required by this artifact. After allowing the experiment script to run for several hours without any further updates, I concluded there was not enough memory available. As pointed out before, perhaps the documentation could be updated to include the specs of a machine known to be capable of fully reproducing the experiments. The files I did manage to retrieve after the execution of the experiments contained several lines related to opening and closing of client connections/sessions. Since I was not able to identify any values describing access counts or related to the results table in the paper, I could not verify that the prototype matches the results presented in the paper.  

Overall the artifact was straightforward to execute and had thorough documentation (especially after the recent author update), therefore I would recommend its approval regarding these aspects. Unfortunately I cannot vouch for its consistency, due to the issue I described above. However, given that the other reviewers seem to have had success in retrieving some of the results, this seems to be more due to my particular setup than caused by the artifact itself.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. The reviewers noted that the technical complexity of the artefact was very high and yet it was handled well by the use of Docker. The results the committee was able to get, was half as impressive as what you report in the paper, but that it mostly attributed to the difference in hardware.

Feel free to make some appropriate adjustments before submitting the materials to ACM, @amine-ben, and enjoy your seal of approval.

**Comment by amine-ben** [comment]
Thank you @grammarware, @kolovos, @dstrueber, @silvalex, @tdegueul  for the time and effort invested in our artefact!

I'll certainly take all of your comments and recommendations into consideration before submission.

Kind regards,
