### ISSUE TITLE
[keidel] IDE Portability Problem

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#2]
Submitted by @svenkeidel to https://github.com/grammarware/sle16/tree/master/keidel

**Comment by patrimrodilla** [comment]
The artifact is the plot of the file lengths and the plot of the respond times of Monto. The artifact instructions and **documentation is clear** and I did not have any problem to fulfill the previous requirements and to configure the software environment (which is very specific and with several dependencies, but is very well solved by Homebrew utility)

I only recommend to the authors to explicitly inform in future presentations of the artifact that the build process could be take long time. In my case, I did not use (the authors did not said nothing) the recommended Gradle Daemon in order to do a faster building process. So finally, it took me almost 2 hours to built all environment. Of course, this is not a problem if you previously know it, but sometimes during the process it seemed that the built is stopping or failing in some way due to the slow process.

Once you successfully built the artifact, the execution of the benchmarks is **easy and well documented**, and in my case works perfectly. However, I have some concerns about if only this artifact is enough in order to show explicitly The IDE Portability Problem solved.The paper exposes a well defined problem and the IR Monto solution is detailed, but for me this artifact only shows the results, whereas the process is also important. Maybe there are best ways to show how the authors have been solved the problem in Monto. They said “we present a solution to the IDE portability problem based on a language-independent and IDE-independent intermediate representation (IR) for editor-service products. This IR enables IDE-independent language services to provide editor services for arbitrary IDEs, using language-independent IDE plug-ins.”
For me, this is not clear only showing this artifact. It's could be interesting to implement a small demostrator prototype of the IDE Portability Problem solved, in terms, for instance, that the user could write a small program and to see how this program is processed by different IDE's or languages...

Once said that, the artifact is **well documented, consistent**, but I have these **concerns** about if it's **complete** in terms to show the problem solved (for instance in a demostration in live at a conference) and also in terms of **re-using**, which for me it's not very clear.

**Comment by iovinoludovico** [comment]
As @patrimrodilla  said I'm still compiling the execution environment because I had to stop the previous phase since my net was too slow.  First comment I totally I agree with @patrimrodilla that the documentation should report that the process could take a very long compiling phase. The percentage is always blinking at 91%, I hope it's processing.

**Comment by iovinoludovico** [comment]
On my mac 

# Total time: 1 hrs 22 mins 1.787 secs

The execution of the benchmark is well documented, I followed the instruction and everything worked fine. I inspected the folder containing the artifacts and as an example it's consistent, but I guess could be improved the reusability of the tool instructing the user to propose his own example and see what are the portability improvements that the tool can provide. In conclusion the artefacts are consistent as examples for the paper, but the authors should focus on the usability aspects and then provide a documentation not for running the examples but to reproduce a new case study. The instruction on the repository are well written for the first execution.

**Comment by llbit** [comment]
The artifact contains benchmarks of the broker service described in the article and three services for Java: outliner, highlighter, and parser services. The artifact does not seem to contain the editor plugins which are described in the article. It would have been interesting to test the IDE integrations.

I was able to run the benchmark of the services by following the instructions. The services themselves have very simple READMEs which seem to say only how to build the services. I could not find many comments in the source code documenting the design of the services, but there seems to not be a huge amount of code, around 2-3k lines of code for all services. It would be nice to see more documentation about the services, it would help in reusing the services especially for others who are unfamiliar with the code.

The benchmark results seem to match the article fairly well. Here is the graph generated after the benchmark run on my machine:

![roundtriploc](https://cloud.githubusercontent.com/assets/2757386/18417298/cdfb6342-782b-11e6-85ca-52a9fa2f8a6c.png)

The lines for Java Highlighting and Java Outliner are a bit different from the article, but there are so few data points at the large file size end and performance differences are of course expected on a different machine. However, I don't like the smooth lines generated in the graph, especially for large file sizes where there are only a handful of data points, so I edited the plot script to plot the raw data points:

![roundtriploc](https://cloud.githubusercontent.com/assets/2757386/18417313/2f754b2e-782c-11e6-827d-e57f69f2b06a.png)

I do think that the artifact is consistent with the article. The artifact also seems to be complete except for the IDE integrations.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, we would like to stress that the artefacts presented here do not seem to play a major part in the paper they accompany. We have decided that this is not a problem, but perhaps you would like to add a few more words about the IDE plugins to the paper.

Feel free to make some appropriate adjustments before submitting the materials to ACM, @svenkeidel, and enjoy your seal of approval.
