### ISSUE TITLE
[zhu] BX Parsing and Reflective Printing

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#5]
Submitted by @zirunzhu to https://github.com/grammarware/sle16/tree/master/zhu

**Comment by anthonyanjorin** [comment]
Hi,

I'm working through the README file and have gotten stuck while trying to compile `tiger_unambiguous_grammar.by`

I keep getting the following error:
`biyacc: byStr2CST: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`

The installation process worked like a charm, and I've already tried all I can think of to no avail.  Any help would be appreciated!

**Comment by zirunzhu** [comment]
Hi Anthony,

Thank you for notifying me the errors. I have never seen it before...
It seems strange because I have neither used the API `readCreateProcess` nor `runInteractiveProcess` in my code. I guess the problem might be due to some changes in the package "process".
Could you please provide me with more details about the error? Which system and which version of GHC do you use?
I will try to solve the problem.

(I think the executable file byStr2CST should be in your system's $path but I still want to confirm it.)

**Comment by anthonyanjorin** [comment]
Hi,

my specs are:   OX X El Capitan, GHC 8.0.1 (Minimal)

your comment about something being on the path might do the trick.  I did not add `.../Haskell/bin` to my path and just ran `/absolutePathToBiyacc/biyacc` directly.    Let me try to confirm this.

**Comment by anthonyanjorin** [comment]
Yep - seems to have worked!  I should have been more careful and followed the instruction to the letter ;)

**Comment by anthonyanjorin** [comment]
My review:

The artefact provided for evaluation is `BiYacc`, together with a test grammar and corresponding test cases.

I followed the steps in the provided README file on OS X El Capitan with GHC 8.0.1 (Minimal).
The installation worked as described with no problems.  I could also compile and run all tests with the expected output.  

In general, the "artefact" is complete and consistent with the description in the paper, so I recommend the AEC's seal of approval.

I do, however, have a few (minor) comments and suggestions for improvement:
1. `biyacc` could be a bit more friendly and appropriately handle "--help", "--version", etc
2.  The grammar file for `arithmetic expressions` and a few simple tests could be added to the artefact.  In the current state the user is referred to a website that might one day either stop working or be changed, etc.  This is one of the reasons for providing and "freezing" this artefact in exactly its current state (if not you could simply link to a website with everything right?).
3. I was lazy and did not add `.../Haskell/bin` to my path, thinking that it would be ok to just execute `biyacc` by referring to it via an absolute path.  This was my fault as it is stated explicitly in the README, but this could be perhaps emphasised in some way :)
4. I had to make `fireTest.sh` executable via `chmod` before I could execute it.  Perhaps this minor but unnecessary hurdle could be removed.

**Comment by zirunzhu** [comment]
Nice to hear it works now (and passed the test)!
Thanks for the comments. I will handle them tomorrow : )

**Comment by andreamocci** [comment]
Platform: Mac OS X 10.11.6 with Homebrew.

A little suggestion to improve the README file. 
GHC is usually separated from cabal (e.g. on brew). I think you should mention the need of installing cabal as well. Haskell programmers would probably have both in any case, but anyone else should install at least both.

**Comment by andreamocci** [comment]
Hi,

I'm having the following issue when trying to configure biyacc with cabal:

```
BiYacc-0.1.0 andrea$ cabal configure
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: BiYacc-0.1.0 (user goal)
next goal: natural-numbers (dependency of BiYacc-0.1.0)
Dependency tree exhaustively searched.
Trying configure anyway.
Configuring BiYacc-0.1.0...
cabal: Encountered missing dependencies:
MissingH >=1.3.0.1,
natural-numbers -any,
parsec >=3.1,
strict >=0.3.2
```

Cabal installed, happy and BiGUL installed correctly, ghc --version writes on stdout "The Glorious Glasgow Haskell Compilation System, version 8.0.1".

Doing

```
$ cabal install MissingH
$ cabal install natural-numbers
$ cabal install strict
```

Seems the minimal set of packages needed to configure biyacc.

**Comment by zirunzhu** [comment]
Hi,
for a first aid and try, could you please try to manually install these packages by the following commands in terminal:

`cabal update`
`cabal install MissingH`
`cabal natural-numbers`
`cabal parsec`
`cabal strict`

(Or maybe just ust `cabal install` without `cabal configure` will work?)
Maybe cabal is just tell you that you need these packages.

**Comment by andreamocci** [comment]
Thank you! As I wrote in the modified comment above, this set of commands/corresponding packages seems the minimal one to configure and install biyacc. 

```
 cabal install MissingH
 cabal install natural-numbers
 cabal install strict
```

**Comment by zirunzhu** [comment]
Thank you for the feedback. I try to uninstall these packages and see whether by using the single command `cabal install` without `cabal configure` will work better.

**Comment by andreamocci** [comment]
My review:

The artifact submission includes the implementation of the approach described in the paper, BiYacc, corresponding test grammars, some test cases, and a web application to illustrate other examples, that is also available online on a remote demo site. I particularly appreciate this effort from the authors since it makes testing and playing with a proposed approach easier and more manageable.

Except from the minor issues that I found during my tentative to build the application, that were mostly due to my relatively old interactions with Haskell, I found the artifact submission pretty well organized and meeting the expectations.  I was able to run the building scripts and try the online examples. Also, I found the artifact to be perfectly consistent with what was proposed and illustrated in the paper.

By inspecting the source code, I found some minimal documentation that could be useful if anyone wants to build on top of the approach, which is a positive aspect of the artifact.

A really minor issue is related to some typos in the artifact description. I advise the authors to spell-check it again (example: providede, similiar, unambigous, oringinal). I also found some typos in some scripts and/or biyacc, I don't remember where but there was a 'complied' instead of 'compiled'.

**Comment by vnssousa** [comment]
This artifact does what it reports. 

The guide itself was clear and easy to follow. The writing of the guide requires some review, as it has some minor errors.  I would also suggest placing the Haskel Platform as the main installation suggestion, as it also includes Cabal, simplifying the installation process. As the guide goes as far as to explain how to chmod the script for execution, I would also suggest including the instructions to add biyacc and byStr2CST to $PATH.

The execution of the examples behaved as reported, with no issues to report.

I would suggest placing the Haskel Platform as the main installation suggestion, as it also includes Cabal, simplifying the installation process. As the guide goes as far as to explain how to chmod the script for execution, I would also suggest including the instructions to add biyacc and byStr2CST to $PATH.

**Comment by zirunzhu** [comment]
Hi anthonyanjorin, andreamocci, and vnssousa,

I have revised the README.md according to all your suggestions.
Thank you again!

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, in the comments above as well as during the discussion some reviewers pointed out that the problems with `cabal` could have been explained in more detail, and that the documentation in general could be proofread and/or spellchecked for misspellings.

Feel free to make some appropriate adjustments before submitting the materials to ACM, @zirunzhu, and enjoy your seal of approval.
