### ISSUE TITLE
[amorim] Principled Syntactic Code Completion

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#7]
Submitted by @udesou to https://github.com/grammarware/sle16/tree/master/amorim

**Comment by llbit** [comment]
The artifact is an Eclipse package and three Eclipse projects. The Eclipse package contains a Spoofax plugin implementing code completion as described in the paper Principled Syntactic Code Completion. The three projects are demonstrations of the code completion on three languages: MiniJava, IceDust, and Pascal. The MiniJava and IceDust languages appear to be the ones mentioned in the article, while the Ruby implementation discussed in the article is not present.

It was easy to install and run the artifact on 64-bit Linux and 64-bit Windows. The instructions were easy to follow, though I would suggest creating a fresh Eclipse workspace to import the three language projects into. I would say the artifact is easy to (re)use.

The documentation looks complete, and the editor is pretty well intuitive anyway,

Regarding completeness, it would be nice to see a demo of Ruby code completion since that is claimed to be implemented in the article.

I tried running all the examples from the figures in the article in the MiniJava project. Below are the inconsistencies I noticed.

In some figures, e.g. Figure 1, there are actually many more completions available. Note for example that Figure 1 in the article does not show completions for integer literals.

I was not able to reproduce the example in the top half of Figure 10 - it does not give a completion for VarDecl when using the exact same code as in Figure 10. Deleting the first line (x = 21 + 21) and trying again then shows the completion "Var" which seems to be equivalent to "VarDecl".

![screenshot 2016-09-10 15 24 43](https://cloud.githubusercontent.com/assets/2757386/18410783/e3f2a7a8-776a-11e6-8452-162457648651.png)

I was not able to reproduce the example in the bottom half of Figure 10: I followed the figure exactly and the completion inserts code _before_ the `x` instead of reusing the `x`, leading to erroneous code. Here is what the "Add" completion does after I select it with the cursor placed just after the `x` as in Figure 10:

``` java
class Main {
 public int m(int x) {
    x = 12 + 12;
   $VarRef = $Exp;
    x
    return x;
 }
}
```

The following screenshot shows my Eclipse editor after I applied the completion. Note the program is still incorrect and the completion was applied in the wrong place and without reusing the `x` variable:

![screenshot 2016-09-10 15 25 05](https://cloud.githubusercontent.com/assets/2757386/18410785/f213c7b8-776a-11e6-8844-07943e55c948.png)

The top half of Figure 13 was reproducible, but the example in the bottom half I could not reproduce. The "Assign-Add" completion is missing, and if I instead select the "Add" completion I get this result:

``` java
class Main {
    public int m(int x) {
        x = 21 +$Exp + $IDreturn x;
    }
}
```

The other Figures apart from the ones I mentioned above I was able to reproduce.

The artifact appears to have some consistency issues with the paper, and it puts into doubt the claim that the error recovery completions should not yield incorrect programs.

In further testing on the MiniJava project I tried to do error recovery of this incorrect program:

``` java
class {
}
```

I placed the cursor between `class` and `{` and the suggested completions are: "ID" and "Parent". Selecting "Parent" leads to the incorrect program:

``` java
class extends $ID {
}
```

The PascalCompletions project seems to have lower quality completions than the MiniJavaCompletions project in some cases, for example in PascalCompletions it does not insert the multiplication operation when selecting the "MulOp" completion, instead it generates this:

```
myvar := $Expression $MultiplicationOperator $Expression
```

The above example does not contradict the claims in the paper, but it illustrates the completion quality relying on the grammar construction as noted in the Evaluation section.

I am unfamiliar with the IceDust language, but the IceDust implementation seems to work similar to the MiniJava and Pascal implementations. IceDust appears to have the same kind of problem I describe earlier where an error recovery completion just inserts a new expression on the line above the cursor, without fixing the error and possibly introducing new errors. The following screen shot illustrates the action I performed (completion: "MemberValue"), and the state after - it added a new line above `ten =` containing `~MemberRef~ = ~Value~`:

![screenshot 2016-09-10 15 17 35](https://cloud.githubusercontent.com/assets/2757386/18410751/ed64d8b6-7769-11e6-915d-5ab1ccdcc733.png)

Unrelated to the artifact, I found a few small things in the paper that the authors may want to fix if possible:
- Extra comma on page 7 in the sentence "in the third, case, if"
- On page 7: "applies and recurse"
- On page 8: "to the make the"

**Comment by ghost** [comment]
Well documented:

I followed instructions for installation [here](https://github.com/grammarware/sle16/tree/master/amorim) to download and run the IDE on Mac OS. I followed instructions for using the IDE [here](http://spoofax.readthedocs.io/en/latest/source/release/migrate/new_completions_framework.html) to trigger code completion in the IDE.

A minor complaint: Sometimes I could not trigger code completion until I try closing, re-opening, cleaning, refreshing, or building the project. New users might find it hard to get started. It would be great to mention these potential situations in the instructions.

Easy to reuse:

The examples in the artifact seem easy to reuse. The artifact contains three examples. Two of them (IceDust and Pascal) contain working syntax definitions. I played with these two examples and the code completion generated placeholders according to the syntax. I changed the Pascal syntax definition, cleaned and re-built the project, triggered code completion again, and saw updated outputs. The other example (MiniJava) seems to contain an empty syntax (thus the code completion has little clue), and the instructions says that they are intentionally left empty for a course.

For the code completion IDE, the [instructions](https://github.com/grammarware/sle16/tree/master/amorim) provided executable files for download. Where could we find its implementation (Section 5)? It would be nice if the implementation is open-source, so that other researchers can extend your work.

Consistent:

The two working examples (IceDust and Pascal) seem to generate placeholders by extending non-terminal symbols in the syntax definitions, consistent with the paper. I was able to reproduce Figures 1 and 10 in a similar Pascal program. I could not reproduce Figure 13 in Pascal, probably due to the difference in variable declaration syntax.

The figures in the paper seem to be MiniJava programs. Since the MiniJava example in the artifact seems to contain an empty syntax, I could not reproduce the exact same figures in the paper. It would be helpful to make it easier to reproduce the exact same results. That said, this artifact should be sufficient to support that the authors implemented a working code completion IDE that generates placeholders and avoids syntax errors.

Complete:

Section 6 of the paper mentions Ruby, a subset of Java, and IceDust. I could not find Ruby in the artifact. The MiniJava example in the artifact seems to be empty intentionally for education purposes. I tried copying and pasting code snippets in the paper into the `MJCompletions.sdf3` file under the `syntax` directory, but the snippets seem incomplete. It would be helpful to make all the evaluation results easily verifiable.

The artifact contains IceDust and an extra example, Pascal, which are good.

**Comment by altmattr** [comment]
The artefact in question is an extended Eclipse application that implements the syntactic code completion from the paper.  It took a few attempts to get the artefact to work for me, first failing on a small, underpowered linux machine.  Its very possible a reboot of eclipse would have fixed my problem on that machine, as it later did on a more powerful MacOS machine, but everything to do with Eclipse is slow on that machine so it was abandoned as not a fair place to test an Eclipse based tool.  I will note however that the standard "heavyweight Eclipse" problem seemed to be exacerbated by the number and size of dependencies that were required.  This may hamper re-usability, but that's purely speculation at this point.

On my standard desktop machine the installation was quick and clear, only the need to restart Eclipse was missed on my reading of the instructions.  The artefact is complete and consistent with the paper and could be easily re-used.  I have no qualifications recommending this artefact for approval.

**Comment by grammarware** [comment]
During the discussion, we have seen that the submitted artefact is installable but not fully consistent with the paper it accompanies. Unless any committee member champions this entry within the next day, we will consider it for **rejection**.

**Comment by udesou** [comment]
@llbit The issue you encountered when reproducing the figures is caused by caching the parse tables in Spoofax and it is not related with the discussion on the paper. 
If you could test it again by doing the following steps in this order:
- build the MiniJava project;
- copy the two tables `sdf.tbl` and `sdf-completions.tbl` and reload the language (right click the project -> Spoofax (meta) -> Load Language);
- open the `example.mjvc` program and test completions. 

Doing that in this specific order should allow you to get the expected results in all cases you listed.

**Comment by udesou** [comment]
@grammarware, @llbit, @asdfyui and @altmattr:

I have made the following changes in the artifact:
- I have added the Ruby implementation we tested our approach on.
- I have also added a fresh version of Spoofax where copying the MiniJava parse table is not necessary anymore. 
- Finally, I have also edited the README file pointing to Spoofax troubleshooting (for problems one might run into when installing Spoofax), to the implementation (I have created a tag on github to the respective branches/repositories used to build Spoofax in this artifact), and created a better explanation of common issues in Spoofax/Eclipse (which are unrelated with the approach we describe in the paper).

**Comment by llbit** [comment]
@udesou I followed the original README instructions regarding copying `sdf.tbl`, and `sdf-completions.tbl` before I tried to reproduce the figures in the article. I redid the same again using your updated instructions (Spoofax (meta) -> Load Language) and got the same result.

I re-downloaded the Windows x64 eclipse package and re-downloaded the artifacts. I then followed the instructions to import MJCompletions into a fresh workspace. This is what I get:

![screenshot 2016-09-14 00 42 29](https://cloud.githubusercontent.com/assets/2757386/18494037/2b008466-7a14-11e6-9eb5-996c8bf9611a.png)

It's obviously not parsing and highlighting the code, so I guess something needs to be rebuilt. I tried restarting eclipse and that did not fix it. I tried Project -> Rebuild All, and no change. I tried closing the editor and then opening it again and then it looked like this:

![screenshot 2016-09-14 00 44 26](https://cloud.githubusercontent.com/assets/2757386/18494083/6eb38c26-7a14-11e6-831f-2c2bf58319d5.png)

Now the editor is behaving strange however - any code I manually type is not parsed, only code that I use completions to produce. Example after just creating a new class using a completion and then typing the `int x = 3;` statement:

![screenshot 2016-09-14 00 45 32](https://cloud.githubusercontent.com/assets/2757386/18494136/b223f040-7a14-11e6-8a2b-ba491d757ea5.png)

I typed some more and then closed and opened the editor again and now the syntax highlighting is gone again:

![screenshot 2016-09-14 00 47 41](https://cloud.githubusercontent.com/assets/2757386/18494172/e0b18544-7a14-11e6-9966-eec04114039a.png)

I cleared the editor and started again by using only completions and got into this very strange state - previous version of the artifact showed completions for parameters in this state:

![screenshot 2016-09-14 00 48 47](https://cloud.githubusercontent.com/assets/2757386/18494200/1959d45a-7a15-11e6-9d49-a4a45a1593dc.png)

Edit: I guess this state is not strange since the main method seems to be part of the grammar now.

The artifact in the current state seems to be working worse than previously for me. I have not yet been able to reproduce the figures in the article with the current version of the artifact.

Update: The current MiniJava grammar seems like it only accepts one statement in a very simple main class:

![screenshot 2016-09-14 01 00 07](https://cloud.githubusercontent.com/assets/2757386/18494480/a24b5436-7a16-11e6-8928-d7257a230b70.png)

No more completions are available after adding one statement, making it impossible to reproduce some of the figures in the article:

![screenshot 2016-09-14 01 01 57](https://cloud.githubusercontent.com/assets/2757386/18494534/f12c659a-7a16-11e6-9398-1e5d808feb8f.png)

**Comment by udesou** [comment]
@llbit It seems like the lack of the MiniJava grammar created the confusion.
A correct MiniJava program follows [this syntax](http://www.cambridge.org/us/features/052182060X/mjreference/node3.html).
But that is interesting already. The examples you showed are guiding you through the correct syntax (even though you did not know it) but the problem is that you expected different results (based on Java, or another MiniJava implementation). 

I added that Grammar to the `README.md` file and that should clear things up.

edit: You should be able to reproduce the figures in the article by either:
- adding a block of statements in the main class.
- keeping the main class (a placeholder is also fine) and do the figures in a separate class.

**Comment by llbit** [comment]
I tried again now to reproduce the figures by leaving the MainClass and creating a separate class "Main" in the same file. Now most of the figures are reproducible. Figure 10 which previously did not work now works. I still found some inconsistencies:

Triggering completion for a placeholder does not work. (Figure 1, subfigure 2). Note this happens when I try selecting a completion without already being in the completion mode - where rectangles are drawn around the placeholders.

Triggering multiple nested completions sometimes works and sometimes does not work. After trigger completion leading to a terminal being placed (int), I can not trigger completions for further remaining placeholders even after using Tab to select them. However, if I manually type an identifier and then press Tab to go to the next placeholder then it will show a list of completions.

**Comment by udesou** [comment]
@llbit 

I could not reproduce the inconsistency in Figure 1, subfigure 2. Unless it is a lexical placeholder you should get the possible expansions for that sort.

This is what I get when I trigger completion on a non-lexical placeholder, and not in linked mode:

![screenshot 2016-09-14 09 37 05](https://cloud.githubusercontent.com/assets/6407960/18503741/e89ba092-7a5e-11e6-9789-1615e6f78dab.png)

With respect to nested completions and the case where you insert a single terminal (int).

When I trigger completion in this case:

![screenshot 2016-09-14 09 47 41](https://cloud.githubusercontent.com/assets/6407960/18504239/8e687cd2-7a61-11e6-8473-d8f1e99e5d6f.png)

The result I get after selecting `int`:
![screenshot 2016-09-14 09 36 41](https://cloud.githubusercontent.com/assets/6407960/18503782/185d5b4a-7a5f-11e6-9ed3-2c7b8d189288.png)

Note that the cursor is located after the `int x;`, and if I press TAB once:

![screenshot 2016-09-14 09 36 49](https://cloud.githubusercontent.com/assets/6407960/18503809/383ae018-7a5f-11e6-9429-2b8cc968e129.png)

I do not know how to tackle the issues you are describe as I am not able to reproduce them here. What you can do so I have an idea of what is happening is to record a video using the framework, showing what are the results you are getting and what you expected instead.

**Comment by llbit** [comment]
@udesou Oh, I see, you placed the cursor inside the placeholder. I tried placing it just at the end of the placeholder, and also selecting the whole placeholder - it worked in the previous version of the artifact. Now I am able to expand all placeholders even in "non linked" mode.

I can now reproduce all the figures in the article so the MiniJava artifact seems to be consistent.

It would have been much easier to reproduce if the two versions of the artifact behaved more similar.

**Comment by llbit** [comment]
In my opinion this artifact could be approved in the current state.

**Comment by grammarware** [comment]
With the championship of this artefact by @llbit, I hereby on behalf of the Artefact Evaluation Committee of SLE 2016 declare it **approved** for inclusion as auxiliary material for the publication. Jesper seems to have gone deeper than his fellow reviewers into the artefact, examined it and found inconsistencies which have since then been fixed. We strongly encourage the authors to update both the artefact itself and its documentation for the final submission.

Please make the appropriate adjustments before submitting the materials to ACM, @udesou, and enjoy your seal of approval.
