### ISSUE TITLE
[kuehn] Full-fledge Role Modeling Editor

### ISSUE THREAD

**Issue by grammarware** [grammarware/sle16#9]
Submitted by @Eden-06 to https://github.com/grammarware/sle16/tree/master/kuehn

**Comment by iovinoludovico** [comment]
The evaluation has been very easy since the virtual machine worked for me like a charm. The editor seems to be very consistent with the description: I tried to add some role, change it, explode/implode it with  the step in and out, and finally I generated the source code in python. I also tried to execute it from the console but I received some errors that I guess do not depend from the generated files. So in conclusion it seems to me very consistent, easy to use and well documented. I have only 1 remark: to evaluate the bundle you need to download 2GB of virtual machine :)

**Comment by rominaeramo** [comment]
The artifact provided for the paper with title "Full-fledge Role
Modeling Editor (FRaMED)" consists of a virtual machine packed with
the ready to use modeling editor FRaMED. Unfortunately, I failed to
open a session for the virtual machine framed-ubuntu. In particular,
this error occurred: Kernel driver not installed (rc=-1908). However,
I suppose it is due to me.

However, the authors provided a detailed documentation that specifies
also alternative methods to install FRaMED. In particular, I
successfully installed it within Eclipse via Updatesite. I tested the
role modeling editor by graphically specifying compartments, objects,
roles, and relationships.

As suggested in the documentation, I looked for more information in
the GitHub Wiki. I imported one of the available examples called
Bank.crom_dia and successfully used it in the editor. Then, I tried to
generate the SCROLL source code (_.scala file) but the operation is
not available; I tried to generate the formal CROM (_.py file), but
its execution generate the following error:
File ".../Framed/src/My1.py", line 3, in <module> from crom import *
ImportError: No module named crom.
Even in this case, the error could be due to other causes.

In general, the artifact is complete and consistent, therefore I
recommend this work for the AEC's seal of approval.

On 6 September 2016 at 22:30, Dimitris Kolovos notifications@github.com wrote:

> Assigned #9 to @rominaeramo.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Romina Eramo, Ph.D.

Dipartimento di Ingegneria e Scienze dell'Informazione e Matematica (DISIM)
Università dell'Aquila, Italy
email: r.eramo@gmail.com
www:  http://www.rominaeramo.it

On 6 September 2016 at 22:30, Dimitris Kolovos notifications@github.com wrote:

> Assigned #9 to @rominaeramo.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Romina Eramo, Ph.D.

Dipartimento di Ingegneria e Scienze dell'Informazione e Matematica (DISIM)
Università dell'Aquila, Italy
email: romina.eramo@univaq.it
tel: 0862 433173
www: http://www.di.univaq.it/romina.eramo

**Comment by jlcanovas** [comment]
The artefact is part of the submission "Full-fledged Role Modeling Editor (FRaMED)" and presents a graphical modeling editor for role modeling. 

The artefact has been deployed and tested using Virtual Box 5.1 running on a Win10 machine with i7 and 8 gb of RAM. 

The deployment of the virtual machine was correct and no problems were detected. It was very easy to access to the Eclipse installation and to start using the proposed modeling editor. The fact that the tool automatically opens an example model also helps to visualize the proposal.

I tried some editor features (e.g., creating/deleting elements) and steping in/out. Everything worked fine. One comment regarding the toolbar when steping in: icons for connections should be different to help distinguish them.

The generation of SCROLL code was not possible to be tested as the tool indicates that such operation is not available. The generation of Formal CROM was triggered without errors (although better error control could be provided when the target file already exists). No further testing with the Python code was performed.

**Comment by iovinoludovico** [comment]
"The generation of SCROLL code was not possible to be tested as the tool indicates that such operation is not available" . I can confirm what @jlcanovas  said , same error for me, so this is the only problem I see in this artefacts evaluation. All the other parts of the tool seem to be fine also considering the demo data provided by the authors that make the evaluation easier.

**Comment by Eden-06** [comment]
@rominaeramo: For the Python script to work, the corresponding crom.py library must be placed in the same folder as the My1.py file. This is part of yet another repository and can be found [here](https://github.com/Eden-06/formalCROM/blob/master/crom.py).
@iovinoludovico: There appears to be different version in the vm, than the current release. Yet, I think this could be updated easily.
@all: What would be a better format to submit a modeling editor as an artefact.

**Comment by grammarware** [comment]
The Artefact Evaluation Committee of SLE 2016 has reached the conclusion yesterday during the committee meeting that this artefact conforms to the expectations and is **approved** for inclusion as auxiliary material for the publication. However, none of the reviewers seemed to be able to make the SCROLL code work. Since this is just one of the possible targets, we have decided that it does not severely undermine the quality of the artefact. However, if at all possible, please either document the way to get it running more exactly (as in including the VM version number, etc), or make sure the artefact is complete otherwise. Besides the problem with the Scala code, the reviewers applauded your use of the virtual machine image, so I guess it is the right format to submit the artefact after all.

Please make some appropriate adjustments before submitting the materials to ACM, @Eden-06, and enjoy your seal of approval.

**Comment by Eden-06** [comment]
Everything is patched by now. I'm really grateful that SLE includes an artefact evaluation process.  Our research must be reproducible.
